### ISSUE TITLE
Does all of our code need to be written during the competition?

### ISSUE THREAD

**Issue by ekunuke** [github/game-off-2012#5]
Say we have a game engine we've written previously. Is it all right to re-use it?

What if we have an unfinished prototype? Is it all right to take this opportunity to flesh out old toys?

**Comment by leereilly** [comment]
I think reusing game engines is fine since we're encouraging people to use open source game engines, libraries, etc. already. Fleshing out an old game though would probably be unfair to other participants, so I'll lean towards a **no** on that one.

Cheers,
  Lee :beers:

**Comment by DreadKnight** [comment]
I have a free open source game project here on github.
It's a rather old project but only recently it took off regarding coding, since it doesn't uses an existing 3rd party engine and barely any libs at all and it was really hard finding a good lead coder.
The project is www.AncientBeast.com and it's already on github
https://github.com/FreezingMoon/AncientBeast

Developer preview playable over at http://AncientBeast.com/combat (keep in mind it's very early and it will get into the contest theme better pretty soon).
I don't really care for winning but I thought that this contest could mean free exposure for the project, which might improve it's fate a lot.

It would be nice if Ancient Beast can participate (without having to push the code to the contest branch as well, perhaps using a submodule) as it's a very serious project that won't get laid down anytime soon, unlike most of the games that are made specially for this competition.
